### ISSUE TITLE
disableTouchEvent doesn't apply if we provide markingType props to the calendar

### ISSUE THREAD

**Issue by codingkapoor** [wix/react-native-calendars#1000]
## Description

`disableTouchEvent` doesn't apply if we provide `markingType` props to the calendar.

## Expected Behavior

`disableTouchEvent` attribute provided to `markedDates` should disable the touch even on the given date.

## Observed Behavior

What actually happened when you performed the above actions?

The touch event is not disabled. However, as soon as you get rid of `markingType` prop to the calendar, it touch gets disabled.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: 1.214.0 
* `npm ls react-native`: 0.59.8

Also specify:

1. Phone/emulator/simulator & version: Andriod Studio Emulator

**Comment by Inbal-Tish** [comment]
@codingkapoor I can't reproduce the issue. Can you add a code snippet and more details on the devices you test with?

**Comment by chenei** [comment]
@codingkapoor 
This issue has been closed because there has been no response to our request for more information from the original author. 
With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
