### ISSUE TITLE
_reactNative.AccessibilityInfo.isScreenReaderEnabled is not a function.

### ISSUE THREAD

**Issue by Biplovkumar** [wix/react-native-calendars#1084]
## Description
Everey time when i update this library it is giving error.
its a bug of this library.
 Step 1 :- Go in Expendable calender index.js and Hide _reactNative.AccessibilityInfo. Function.
Step 2 :- Add Component Did mount then  _reactNative.AccessibilityInfo. Function.
Image attached.
then Error resolved else error showing.

## Expected Behavior

No need to change Node modules file after update the library.

## Observed Behavior

Need to change Node modules file after update the library.

```
Error text goes here!
```
![Simulator Screen Shot - iPhone 8 - 2020-03-05 at 13 11 09](https://user-images.githubusercontent.com/30401136/75964084-9d259480-5eec-11ea-9947-dfbac3cc21c7.png)
![Screenshot 2020-03-05 at 1 18 52 PM](https://user-images.githubusercontent.com/30401136/75964110-a44ca280-5eec-11ea-97f5-4fccc8d31c08.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:  ^1.264.0
* `npm ls react-native`:   "0.59.9",

Also specify:

1. Phone/emulator/simulator & version:  AllVersions.

## Reproducible Demo

![Screenshot 2020-03-05 at 1 19 54 PM](https://user-images.githubusercontent.com/30401136/75964208-cd6d3300-5eec-11ea-995c-3cc5c26d095c.png)

Need to write every time in Nodemodules index file.

**Comment by chenei** [comment]
I am accepting your solution.
Will submit a PR.

**Comment by eviliana** [comment]
The solution on PR [7e0b1fc](https://github.com/wix/react-native-calendars/commit/7e0b1fcdcdf3e9ea51e603497ac574729b7f25d8) crashes for RN version `0.59.9` because method isScreenReaderEnabled is not supported according to [official docs](https://reactnative.dev/docs/0.59/accessibilityinfo). As per @Biplovkumar 's solution, the usage of AccessibilityInfo is different for backwards compatibility
