### ISSUE TITLE
calendar not working with iOS

### ISSUE THREAD

**Issue by shubham-ntz** [wix/react-native-calendars#1103]
Hi, I've just installed the module and implemented the sample example, in Android it is working fine but i'm getting issue on iOS. I've Attached snapshot issues i'm getting in iOS platform.

![Simulator Screen Shot - iPhone 8 Plus - 2020-04-02 at 18 17 49](https://user-images.githubusercontent.com/61586664/78334283-204c1000-75a9-11ea-8f71-ec69fe8f6004.png)

**Comment by ArkaneKhan** [comment]
I too am having the same issue it working fine on android and throwing above error on IOS.

**Comment by nathsimpson** [comment]
Can you share your code?

**Comment by ArkaneKhan** [comment]
my react native version is 0.59 it was probably happening because of this
downgrading library version solved my issue. Below is the code.

render() {
const { canSelectDate } = this.props;
const { marked } = this.state;
return (
<View>
<Calendar
onDayPress={(day) => canSelectDate && this.onDayPress(day)}
style={{
width: Metrics.screenWidth,
}}
markedDates={marked}
minDate={moment().format("YYYY-MM-DD")}
markingType={"period"}
theme={THEME}
/>
</View>
);
}

**Comment by chenei** [comment]
Hi @ArkaneKhan ,
Did you solve the issue?
