### ISSUE TITLE
ExpandableCalendar doesnt render calendar  on expendad swiping left or right the next month

### ISSUE THREAD

**Issue by rodinhatokay** [wix/react-native-calendars#1274]
## Description

in ExpandableCalendar on expanded header month doesn't match the calendars name on middle
and on changing month it doesn't show the dates only name of the month that doesn't match the header month 

## Expected Behavior

I copied and pasted from example src and issue occurs 

## Observed Behavior
initial display is ok its showing the current month but on swipe(left or right)/on click changing month, the month header
doesn't match the month name display on and it doesn't load the date 
before changing month: 
![start](https://user-images.githubusercontent.com/57593612/90884785-0de83c80-e3b9-11ea-9f39-7fa32572f0cd.png)
after changing month: 
![issue](https://user-images.githubusercontent.com/57593612/90884798-13de1d80-e3b9-11ea-950f-6850a108ebda.png)

## Environment

Please run these commands in the project folder and fill in their results:

react-native: 0.61.0
react-native-calendars: 1.314.0
using emulator nexus 5x API 29

## Reproducible Demo
I'm using RTL in react native causes the issue 
setting the next following code to false makes the issue disappear to false.

`ReactNative.I18nManager.allowRTL(true);
ReactNative.I18nManager.forceRTL(true);`

anyway to avoid the issue without setting the whole app to LTR ?

**Comment by GualbertoVannini** [comment]
@rodinhatokay did you find any solution? I am having the same issue

**Comment by rodinhatokay** [comment]
@GualbertoVannini  no i ended up using Calendar component

**Comment by GualbertoVannini** [comment]
@rodinhatokay I have found this workaround:
looks that this issue  is connected somehow only with **horizontal={true}**.
What I made is:
1. if RTL is setted to **true** using the calendar with  **horizontal={false}** and  **pagingEnabled={true}**. 
2. set on the parent view the perfect height just to show the first month and not all months that are below all in vertical 
one after the other. 
![Screenshot 2021-06-08 at 09 21 49](https://user-images.githubusercontent.com/52403416/121141188-fe988980-c83a-11eb-8176-9d2a71b58841.png)
3. using the pagination to move through months instead of the scrolling vertical that is not allowed from the parent view 

I confirm that this problem for me is only with RTL setted to true, only Android and only connected with  horizontal={true}
