### ISSUE TITLE
Can't scroll weekCalendar to next/prev month

### ISSUE THREAD

**Issue by DonOzOn** [wix/react-native-calendars#1304]
I cant scroll pre/next month in this week-calendar of react-native-calendar , It seem to back pre week instead of go to next month
```
<WeekCalendar
                            hideDayNames={true}
                            firstDay={1}
                            dayComponent={this.renderDate}
                            theme={calendarThemes}
                            allowShadow={false}
                            markedDates={{
                                ...this.state.markedDates,
                                [this.state.selectedDate.dateString]: {
                                    selected: true,
                                },
                            }}
                            pastScrollRange={(new Date().getFullYear() - 1900) * 12}
                            futureScrollRange={(2099 - new Date().getFullYear()) * 12}
                            current={this.state.selectedDate}
                            onDayPress={(date) => this.changeDate(date.dateString)} />
```
https://i.stack.imgur.com/3a27g.gif

**Comment by emilisb** [comment]
Hi, this issue happens because you don't wrap `WeekCalendar` with `CalendarProvider`. `WeekCalendar` is not supposed to be used as a standalone component. We will add docs for this component and we will mention this.

Please look at the example here: https://github.com/wix/react-native-calendars/blob/0f7037bdcaaa2ecce3b2d992c55c2b0b8d33fb51/example/src/screens/expandableCalendar.js#L175

**Comment by DonOzOn** [comment]
@emilisb you alright , i fixed it by delete props 'current' and follow your example , thanks so much
