### ISSUE TITLE
Agenda week not work First loading

### ISSUE THREAD

**Issue by methineeinkan** [wix/react-native-calendars#1324]
![Screen Shot 2563-11-10 at 09 09 32](https://user-images.githubusercontent.com/40588602/98618792-7ac5ff80-2334-11eb-9d98-8f7f3874d870.png)

**Comment by maxgenest** [comment]
related to https://github.com/wix/react-native-calendars/issues/1228. But it still has no solution

**Comment by mjcrouse** [comment]
this seems to be related to the past and futureScrollRange. I found when values are <12 this happens, or something similar, like the month or days of the week appearing instead of the dates. This still happens as you get close to the start and end of your scroll range, but increasing those values can prevent it from happening where you are usually using the calendar.
