### ISSUE TITLE
Suggestion: Day-dot below the day

### ISSUE THREAD

**Issue by greew** [wix/react-native-calendars#140]
A quick question:

I have a client, who requires that the dot under the day (in Calendar basic view) is located underneath the large circle, when a date is marked.

I have changed the default behavior in a fork, but if you're interested, I'm willing to make a PR with an option to select this behavior.

I've attached an example

![screenshot_20170816-092214](https://user-images.githubusercontent.com/189321/29351970-3d0d6048-8265-11e7-8149-ad6ad1da2ae4.png)
![screenshot_20170816-092313](https://user-images.githubusercontent.com/189321/29351969-3d0b3174-8265-11e7-88a3-ecaa888f90a8.png)

**Comment by tautvilas** [comment]
hi, thx for info. Does this also look good in agenda view?

**Comment by greew** [comment]
No idea - I haven't looked at agenda view yet, but I'll give it a try - hopefully within the next few days.

**Comment by tautvilas** [comment]
If you do a PR I would prefer that you would implement this marking type as a new day component. You can see how interactive/basic markings are separated here:
https://github.com/wix/react-native-calendars/tree/master/src/calendar/day

the api would be that if library users choose `markingType={'dotUnder'}` they would get your marking style, otherwise - default style

**Comment by YeeWan0217** [comment]
@greew hi, may I know how you change the code in order to get the appearance above?

**Comment by greew** [comment]
Sorry, I haven't worked on this project for several years and don't have access to the source code anymore.
