### ISSUE TITLE
Agenda header's bug

### ISSUE THREAD

**Issue by hayukataishi** [wix/react-native-calendars#1440]
I'm Japanese.
I'm sorry for my poor English.

## Description

Agenda's header does not work.

![IMG_7282](https://user-images.githubusercontent.com/46618767/111397080-c41fc480-8703-11eb-9036-451eca28e5e4.PNG)
![IMG_7283](https://user-images.githubusercontent.com/46618767/111397112-d7329480-8703-11eb-82aa-7c979f348a4d.PNG)
 
## Expected Behavior

I remove yarn.lock and node_modules.
after that "yarn install"
Then this bug was happen.

## Observed Behavior

always happen.

## Environment

Please run these commands in the project folder and fill in their results:

>yarn list react-native-calendars
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ react-native-calendars@1.1254.0
yarn list react-native
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ react-native@0.63.4
✨  Done in 1.02s.

Also specify:

Phone/iPhone7 iOS 14.4
Simulater/iPhone12

**Comment by felipe-fator3** [comment]
Same problem here in  a Vanilla JS React Native project using NPM.

In my package.json I have: "react-native-calendars": "^1.1254.0"

![image](https://user-images.githubusercontent.com/70180009/111475708-254b9600-870c-11eb-96c5-cbe703537936.png)

Also, when I try to move the knob, sometimes both header and knob disappear forever.

Here is how I'm using the Agenda component:
```html
<Agenda
  style={{
	flex: 1,
	width: '100%',
  }}
  items={{
	'2021-05-22': [{name: 'item 1 - any js object'}],
	'2021-05-23': [{name: 'item 2 - any js object'}],
	'2021-05-24': [],
	'2021-05-25': [
	  {name: 'item 3 - any js object'},
	  {name: 'any js object'},
	],
  }}
  renderItem={(item, firstItemInDay) => {
	return (
	  <View
		style={{
		  flex: 1,
		  justifyContent: 'center',
		  alignItems: 'center',
		}}>
		<Text>{item.name}</Text>
	  </View>
	);
  }}
  selected={'2021-05-22'}
  minDate={'2021-01-10'}
  maxDate={'2021-06-30'}
/>
```

This may be related to #1360 since I'm getting exactly the same error described in that issue and this sure looks like a style-related bug.

**Comment by hayukataishi** [comment]
@felipe-fator3 
Thank you for reply.

I tried style comment out.
>            // agenda container style
            // style={{
            //   flex: 0.8,
            // }}

Then this bug does not appear.
I just do that for now.

**Comment by Fator3** [comment]
Thx, @hayukataishi . by removing the `flex: 1` style, the header worked fine.
