### ISSUE TITLE
CalendarList rendering super slow

### ISSUE THREAD

**Issue by mleister97** [wix/react-native-calendars#1453]
I am facing performance issues with the CalendarList.

- Tested on Samsung Galaxy S9 and OnePlus 3
- I am using 12 months in total to display
- I am using expo, the build-version is a little bit faster but still very slow.
- Using version 1.1255.0 (latest one) of react-native-calendars

```js
const [show, setShow] = useState<boolean>(false)

<SafeAreaView style={styles.container}>
    <View style={{flex: 1}}>
        <Button title={"Toggle calendar"} onPress={() => setShow((s) => !s)}/>
    </View>
    <View style={{flex: 9}}>
        {show &&
        <CalendarList
            // style={{width: deviceWidth}}
            onDayPress={handleDayPress}
            markedDates={{
                [selectedDate]: {selected: true}
            }}
            theme={{
                selectedDayBackgroundColor: colors.primary,
                todayTextColor: colors.primary
            }}
            pastScrollRange={12}
            futureScrollRange={0}
            scrollEnabled={true}
            showScrollIndicator={true}
        />
        }
    </View>
</SafeAreaView>
```

**Comment by mleister97** [comment]
https://user-images.githubusercontent.com/16700053/113883872-d64ec900-97be-11eb-870e-d0500a7f01e1.mp4

**Comment by carloslibardo** [comment]
I'm facing the same issue.

**Comment by callaars** [comment]
I think that this will the issue no matter what since it is just a large list. The best thing - in my opinion - what you can do is render the component but hide it by setting the parent view height to zero. Then when you toggle it just set the height and voila a smooth transition.

Of course you'll need to flash it out so it looks good, but what you're doing here is rendering initially and hoping it will immediately display correct. I don't think that's ever going to happen.

**Comment by mleister97** [comment]
@callaars How can a component like this be so slow? Thanks for your hint but in my oppinion this is a very critical issue for a basic calender like this (I know it also supports way more complex features). A component containing arround 40 text views just cannot be that slow. This seems like major performance issues or any bug

**Comment by callaars** [comment]
I think you are misunderstanding a core concept here. On React Native all the date calculations and layouting (in this package) are done on the JS thread. The JS thread is single threaded, it can only handle so many permutations before it starts lagging. This is the core frustration for a lot of React Native developers. 

Not that it would affect performance too much, I think you also misunderestimate how many components are being rendered by the calendar. If you look at this little loom I made you can see that it at least renders one month before and one month after: https://www.loom.com/share/12ad056dd0a7407589cf49cb913ba411

As I said though, **rendering** is never the issue as that's on the Native side and that's fast enough. It's the permutations on the JS side that are the problem.

To overcome this problem you have to be smarter how you develop and don't just assume all components will have a blazing performance, because simply said that's just not the case. 

My main tip still stands and I will reiterate it a little. Basically what you want to do is render the component even if it isn't activated yet. In this loom you can see that I can open the calendar smoothly in one go, that's because I render it in a `height: 0` view inside a `Suspense` component. That way it is loaded as soon as the application is done loading, and therefor immediately showable.

In your case, and correct me if I'm wrong, you're rendering the component once you click on the button, and not earlier. That will never give you the performance you require.

See demo: https://www.loom.com/share/2e308976ea5245b386175bd6d8521249

**Comment by mleister97** [comment]
Thanks a lot for pointing that out. I tought Layouting as well as the basic components are calculated natively.

What's the name of the debugging tool you used in loom? 

Still, as shown in your video I think the components (actually the tree and layouting) could have been done better (more performant with less components).

Your tip is a great workaround. Thank you so much. Could you share your code snipped you have used (also for other people)? So the suspense height 0 trick. Would be so great! :)

**Comment by pycraft114** [comment]
Still having performance issue with ExpandableCalendar in android. Any news about this?

**Comment by venux92** [comment]
@callaars I tried you solution without success.
The issue for me is only on Android, iOS is fine. 
I even tried to have the Calendar without any `markedDates`  very basic and it still takes 2-3s to open. On iOS it's instant.

**Comment by ramdhanymf** [comment]
Hi, i would like to share my approach here.. To anticipate load time issues, I initialized my screen with some lighter component like ActivityIndicator and as soon as the screen get rendered, I replace ActivityIndicator with CalendarList. To achieve this you can use a combination of useState() with true as init value, then set state to false inside useEffect().

`
const [isLoading, setIsLoading] = useState(true);

useEffect(() => {
     setIsLoading(false)
}, [])

if(loading){
return <ActivityIndicator />
else{
return <CalendarView />
`

**Comment by chrise86** [comment]
This is definitely not stale, I thought I had some kind of endless loop when I encountered this because the performance is so bad.

**Comment by charlyBerthet** [comment]
Same issue here. It works fine on iOS but rendering the calendar on Android is really really slow

**Comment by Simba-Mupfunya** [comment]
same here @charlyBerthet

**Comment by NyashaNziramasanga** [comment]
I was having performance issues as well and decided to use [react-native-calendario](https://react-native-components.gitbook.io/calendar/) because of the way its implemented and I only needed the CalendarList with no performance hit

**Comment by albbus-stack** [comment]
This is issue is not in any way stale and it's a major pitfall when using this library.

There is also a major problem using the Agenda component since it cannot be rendered consistently without the actual layout. 
If you try pre rendering the agenda in a non lazy tab navigator the Agenda week will be out of place. This means that I cannot load the Agenda page on app load but only when the user switches to that particular tab, resulting in the waiting time discussed above.
It seems to me that no workaround is really feasible in this situation, any ideas are more than welcome.

**Comment by zhGio** [comment]
@albbus-stack i'm also facing the same issue and even considering abandoning the project since i've built the idea around the agenda + timeline

**Comment by ahvenainen** [comment]
I'm having terrible performance issue with ExpandableCalendar. Has anyone found a solution to this?

**Comment by talal-tilted** [comment]
I am using it with CalendarList, extremely slow on both ios and android

**Comment by Renbo-Studio** [comment]
Same with me, but as i removed the Theme, it stopped lagging.

**Comment by aymericdelaforcade** [comment]
I found a solution. Oddly enough it was the `theme `property that slowed down the component for me. I defined the theme in a `StyleSheet.create` and everything works!

For more optimization, you should not put the `key` property

Example code:

````
<CalendarList 
      //key={new Date()} you should also disable this 
      theme={calendarTheme} //HERE
      calendarWidth={scale(340)}
      markedDates={markedDates}
      firstDay={1}
      style={{height: verticalScale(220), marginTop: '15%'}}
   />



const calendarTheme = StyleSheet.create({
    'stylesheet.calendar.header': {
        monthText: {
        marginBottom: '5%',
        fontSize: 20,
        },
        week: {
        padding: 0,
        justifyContent: 'space-around'
        }
    },
    'stylesheet.day.basic': {
        base: {
            width: 32,
            height: 32,
        }
    },
    backgroundColor: '#353535', 
    calendarBackground: '#353535', 
    monthTextColor: 'white', 
});

>

**Comment by benjaminliang2** [comment]
Oct 2024: CalendarList is still very laggy when selecting dates. Using expo go on ios simulator and android simulator
`
"expo": "51.0.35",
"react-native-calendars": "1.1307.0",

`

**Comment by Nikita2k** [comment]
I'm not sure why it's closed, I can still easily repro on iOS in Expo. Even `onDayPress` is taking up to a second to execute

**Comment by iyyappanGitHub** [comment]
Same here,
OnDayPress takes 1.5s to render the calendar component again.

**Comment by wannesmatthys** [comment]
Yep... same here with day press. Did anyone figure this one out?

**Comment by mi2468** [comment]
In my home screen i have a card if i click card it navigate using navigation .navigate but it slowly navigate  this issue is happened because of <Agend /> any on e solve me this issue in react native

**Comment by gregoripolak** [comment]
We use `CalendarList` and the app is just soooooo slow all of the sudden, why??
