### ISSUE TITLE
Use @types/react-native-calendars instead of default  react-native-calendars types

### ISSUE THREAD

**Issue by Navipro70** [wix/react-native-calendars#1652]
## Description

Default typescript types from `react-native-calendars` are not correct. I want to use `@types/react-native-calendars`, because this lib define types right

## Expected Behavior

Correctly define types for lib

## Observed Behavior

`react-native-calendars` not correctly define types, some types are incorrect or marked with `any`. `@types/react-native-calendars` does not replace them after installation

## Environment

```
"react-native": "0.64.1"
"react-native-calendars": "^1.1255.0"
"@types/react-native": "^0.64.0"
"@types/react-native-calendars": "^1.505.2"
```

## Reproducible Demo
```
 error TS2305: Module '"react-native-calendars"' has no exported member 'DayComponentProps'.

3 import {DayComponentProps} from 'react-native-calendars';
          ~~~~~~~~~~~~~~~~~

error TS2305: Module '"react-native-calendars"' has no exported member 'DateObject'.

3 import {DateObject} from 'react-native-calendars';
          ~~~~~~~~~~

[01:21:39] Found 2 errors. Watching for file changes.
```

**Comment by stami-fb** [comment]
Yeah, it seems the latest release 1.1267.0 had a lot of breaking changes to TypeScript types. :(

**Comment by huynhtrungthoai** [comment]
> Yeah I also suddenly receive TypeScript errors. It worked before, must be some upgrade that introduced this problem. E.g. I get those errors:
> 
> `TS2322: Type '{ monthNames: string[]; monthNamesShort: string[]; dayNames: string[]; dayNamesShort: string[]; today: string; }' is not assignable to type 'locale_detail'.   Object literal may only specify known properties, and 'today' does not exist in type 'locale_detail'.`
> 
> Although the doc clearly mentions that today is a field: https://github.com/wix/react-native-calendars#usage

I add data into locale_detail, this error disappeared

interface locale_detail
{
    monthNames? : string [] | undefined;
    monthNamesShort?: string [] | undefined;
    dayNames?: string[] | undefined;
    dayNamesShort?: string [] | undefined;
    amDesignator?: string | undefined;
    pmDesignator?: string | undefined;
    today?: string | undefined;
}

**Comment by dylmye** [comment]
Current mitigation for this is:
```
"dependencies": {
    "react-native-calendars": "1.1264.0",
},
"devDependencies": {
    "@types/react-native-calendars": "1.1264.3",
}
```

**Comment by ulrellik** [comment]
A better workaround, esp. if you want to use recent version, is to just add this to your tsconfig.json:

```
{
  "compilerOptions": {
...
    "baseUrl": "./",
    "paths": {
      "react-native-calendars": ["node_modules/@types/react-native-calendars"]
    }, 
...
}
```

This tells TS to use @types/react-native-calendars instead of the inbuilt types which break everything.

**Comment by Jackman3005** [comment]
@ulrellik I have used your solution for quite some time, but in trying to upgrade to Expo v50 they have update Metro to automatically include `tsconfig.json` paths and configure the resolver. This causes issues because `@types/react-native-calendars` does not actually have implementation code. I have to disable this feature on metro right now and continue to configure the paths manually in `babel.config.js`. 

I would like to switch to using this nice new feature for the benefit of reducing redundancy, __but I don't know another way of overriding the Typescript types of `react-native-calendars` with the types provided by `@types/react-native-calendars`...__

Anyone know of a better way to do this that doesn't alter the `tsconfig.json` `paths` configuration?

Note: I have not actually checked if more recent versions are now providing better type support. Is `@types/react-native-calendars` no longer needed? Why haven't they been merged/deprecated?

**Comment by ulrellik** [comment]
@Jackman3005 I'm no longer using @types/react-native-calendars, they have fixed all TS problem in recent versions.
