### ISSUE TITLE
ExpandableCalendar hardcoded height issue

### ISSUE THREAD

**Issue by DreamakerDimas** [wix/react-native-calendars#1779]
## Description

**ExpandableCalendar** have harcoded open & closed height. Since I use custom **dayComponent** calendar just couldn't be fully opened (just hides last week row).

It is important to me to have closing state & scroll by week as well as opened state & scroll by month.

- Same for 6 weeks months (but in that case it hides two weeks rows).

## Expected Behavior

At least would be grate to have opportunity to set height dynamically or set closedHeight/openedHeight in component props.

**Comment by CesariniFillipe** [comment]
Same issue for me here. I have another issue that doesn't allow me to click on days from another month, both in closed and opened state.

**Comment by peanut-lover** [comment]
same issue for me, need feature to customize weekHeight

**Comment by TNAJanssen** [comment]
Any updates?

**Comment by PoojaAppinventiv** [comment]
I'm also facing same issue

ExpandableCalendar have hardcoded open & closed height. Since I use custom dayComponent calendar just couldn't be fully opened (just hides last week row).

It is important to me to have closing state & scroll by week as well as opened state & scroll by month.

Same for 6 weeks months (but in that case it hides two weeks rows).

**Comment by emmayang0909** [comment]
我修改了源码的 KNOB_CONTAINER_HEIGHT WEEK_HEIGHT的高度  源码中WEEK_HEIGHT * (numberOfWeeks.current)计算出实际需要的周数高度  KNOB_CONTAINER_HEIGHT是用于展开或收起日历视图的滑块部分的高度
