### ISSUE TITLE
renderArrows

### ISSUE THREAD

**Issue by tomelsner** [wix/react-native-calendars#185]
I'm using a function to render left and right arrows. The function checks if the active month (which is in my state) and disabled the left arrow if the calendar is displaying the current month. I'm saving the current visible month in the state to set the current month and to do the calculation. 

My renderArrow function is called before the month change function is called and event through I change the state in the month change function, the renderArrow function is not called again.

Is there a way of forcing the re-rendering of the arrows when the month changes?

**Comment by kuts-denys** [comment]
Facing the same problem. Trying to display months names instead of arrows, and they are always rendering before onMonthChange callback fires and changes the state.

**Comment by benbr** [comment]
As a workaround, you can achieve this by overriding `onPressArrowLeft` and `onPressArrowRight` functions, along with `current` prop. This way your own component holds the state for the current month, instead of using the internal Calendar state.

```
<Calendar
    current={currentMonth}
    onPressArrowLeft={()=>this.setState({currentMonth:previousMonth})}
    onPressArrowRight={()=>this.setState({currentMonth:nextMonth})}
    ...
/>
```

`onMonthChange` and `onVisibleMonthsChange` aren't called anymore when you use the calendar this way, so you would also need to move any use you had of these in your `onPressArrow` functions.
