### ISSUE TITLE
Responsiveness of CalendarList scroll and clicking on dates

### ISSUE THREAD

**Issue by HunterMarrow** [wix/react-native-calendars#19]
Hi, 

There seems to be quite a lag in the scroll of the CalendarList. What seems to happen is while scrolling between months, the month detail will disappear and the month name will only be displayed. This seems to happen when scrolling quickly through the months. 

The second issue with responsiveness is related to selecting days on a calendar. There seems to be quite a lag in the highlighting process while tapping on different days. 

Are there any properties I could use to speed this up? 

Thanks in advance for all your help.

**Comment by tautvilas** [comment]
Hi, what device/simulator are you using? We are constantly working on better performance for this component, but on older devices it can get slow because this component is pure js(non-native) and each calendar is composed of many small views.

The month name that you see while scrolling is part of performance optimisation. The month name is placeholder for months that have not been rendered yet. As soon as months scroll into view they are rendered and if performance is good then placeholder is not seen. If there is some lag you see place holder (which is better than seeing an empty view).

**Comment by HunterMarrow** [comment]
Hi,

Thanks for your speedy response. I'm testing it on a Samsung S4, and an
Android emulator running on windows. I'm sorry I don't have the exact model
numbers but I can send that info to your bit later if you need it?

I really like this component and would really like to use it in my project.
So are you saying if I test it on a newer device that the performance would
be better?

Is there anything I could do to help with this issue?

Thanks for your help.

Regards
Grant

**Comment by tautvilas** [comment]
Yes, basically the component will run smoother on newer devices. Also iphone(6 and later) performance seems to be better than similar android models. While running on android make sure you [disable JS Dev Mode](https://facebook.github.io/react-native/releases/0.32/img/AndroidDevSettings.png), to get best performance.

It would be great If you could think of ways how to make the component more performant. Performance increasing pull-requests are always welcome :)
