### ISSUE TITLE
Calendar show wrong date for day

### ISSUE THREAD

**Issue by Jomik** [wix/react-native-calendars#2110]
## Description

Calendar shows the wrong date for a given day if the week starts on a Monday. It shows Friday as 1st of December.
![image](https://user-images.githubusercontent.com/699655/205280763-413183bc-06c0-4d6f-a714-cac01b22b61d.png)

Seems like #1010 was closed without an actual fix. Editing package source files is not a fix.

## Expected Behavior

That it shows Friday as the second of December

## Screenshots

![image](https://user-images.githubusercontent.com/699655/205280763-413183bc-06c0-4d6f-a714-cac01b22b61d.png)

**Comment by yoshiokaCB** [comment]
Same as https://github.com/wix/react-native-calendars/issues/2073 and https://github.com/wix/react-native-calendars/issues/2064 and https://github.com/wix/react-native-calendars/issues/2069

I think we can solve the problem here.
https://github.com/wix/react-native-calendars/issues/2091#issuecomment-1316879705

**Comment by gonca-gul** [comment]
You don't need to intervene directly in the package. Start the day list you provide from Sunday and let firstDay={1}. This solved my problem.
