### ISSUE TITLE
Jump to previous month when the 1st number is selected

### ISSUE THREAD

**Issue by redjohnfrv** [wix/react-native-calendars#2164]
## Description

It's simple: the calendar jumps to the previous month when the first date is selected. Shows this number in the previous month's inactiveDays list instead of showing it in the current month's list.

For example: I have a 1st of September on the September screen. But if I click it - screen changes to August (in August screen also has 1st of September like inactive date).

## Expected Behavior

When 1st day in month is clicked, Calendar doesn't jump to previous month.

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars@1.1293.0
react-native@0.70.6

**Comment by AmitP1392** [comment]
any solutions for this??

**Comment by StefanusChristian** [comment]
My team also face this kind of issue, It seems the reason for this behavior because of different timezone. 

EX: If your local timezone is GMT+7, 1st date on each month between 00:00 AM - 06:59 AM will be considered as yesterday date (30/31 on previous month). 

The error probably in this utils: 
https://github.com/wix/react-native-calendars/blob/master/src/dateutils.ts#:~:text=export%20function%20month,%7D

**Comment by MarcHbb** [comment]
Have you found any solution @StefanusChristian ?

**Comment by hughyyyy** [comment]
Anyone has any solution on this? This makes the calendar unusable.

**Comment by hughyyyy** [comment]
https://github.com/wix/react-native-calendars/issues/2489

**Comment by hughyyyy** [comment]
Creating new issues, this one got closed by the bot.
