### ISSUE TITLE
When opening agenda there is a short 'flick' when it is possible to see calendar expanded

### ISSUE THREAD

**Issue by tautvilas** [wix/react-native-calendars#243]
When opening agenda there is a short 'flick' when it is possible to see calendar expanded.  @overengineered plz advise how to fix I think it could be related to drag implementation.

**Comment by Uzef1997** [comment]
the Issue is still getting produced in the latest version `"react-native-calendars": "^1.1293.0"`,
can you please look into the attached video
as of now, I am simply rendering a calendar with the selected date nothing else
`<Agenda
                selected={'2017-05-16'}
            />`

https://user-images.githubusercontent.com/45681786/221497077-ff752ab8-c1ab-4d8e-a562-5da6cb24de9e.mp4
