### ISSUE TITLE
Load item in Agenda

### ISSUE THREAD

**Issue by sondoan1204** [wix/react-native-calendars#244]
## Description

Excuse me, i do not know if it is not bug but when use fetch() data from websv and have the parameter passed into month. function loadItems(day) returns twice for 2 months. As such, Agenda loads permanently because its load order is November and October but I'm picking November.
How do I handle it?...
log file
[log.txt](https://github.com/wix/react-native-calendars/files/1495382/log.txt)
## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:

Also specify:

1. Phone/emulator/simulator & version:
All ver & all simulator

## Reproducible Demo
![screenshot_1511342789](https://user-images.githubusercontent.com/21288630/33120373-74f22bb0-cfa4-11e7-8313-35ec33de52ed.png)

**Comment by tautvilas** [comment]
probably related to #237

**Comment by tautvilas** [comment]
It's true that loadItems work flaky in this situation, however you should merge results of both loads to same object and pass this items object with complete loaded data to agenda, this way you would not have infinite spinner. Also please check this thread. #24

**Comment by sondoan1204** [comment]
Tks for your reply, 
I saw console.log on demo and recognize you merge results of both loads to same object and pass this items object with complete loaded data to agenda. 
My problem lies in the componentDidMount () function. I passed the external parameter so that it would not happen.

**Comment by kurbur** [comment]
This was an interesting problem that I figured out how to work around very effectively. The solutions listed weren't fully solving my problems with the agenda Items and the need to add or remove items from the agenda and the component update cleanly.

After a couple hours of experimenting, I found that clearing the items initially each time before setting them in the `loadItems` function was causing the agenda to jump and load more than once (looked bad). so instead, I used `loadItems` as an initial loader. basically, it loaded my items the first time and that was it. I used the React hook `useEffect` to listen for a status change on the agenda. When the hook would see a status of `schedule-updated`, it would clear the items by setting it to an empty object and then reload. 

Note: the second useEffect would clear the items on component unmount so that the next time the Agenda loaded in, the loadItems function would be cleared initially. 

I hope this helps someone! It sure solve my issues!

code example: 
` 
 useEffect(() => {
    if(scheduleStatus === SCHEDULE_STATUS.SCHEDULE_UPDATED) {
      console.log("updating Schedule")
      const mappedItems = {}
      setItems({})
      setTimeout(() => {
        for(let event of scheduleEvents) {
          let date = moment(event.startTimestamp * 1000).format('YYYY-MM-DD')
          if(!mappedItems[date]) {
            mappedItems[date] = []
          }
          mappedItems[date].push({
            title: event.title,
            id: event.eventId,
            duration: event.length,
            additionalNotes: event.additionalNotes,
            startTimestamp: event.startTimestamp * 1000,
            assignment: event.assignment
          })
        }
        dispatch(ScheduleAction.setStatus({status: SCHEDULE_STATUS.INACTIVE}))
        setItems(mappedItems);
      }, 1000)
    }
  }, [scheduleStatus])
  useEffect(() => {
    return setItems({})
  }, [])
`
