### ISSUE TITLE
Single/double digit day and month inconsitency

### ISSUE THREAD

**Issue by declandowling** [wix/react-native-calendars#27]
If I select any date where the day or month is below 10 (1st of January 2017 for example), the onDayPress event returns single digits for the _day_ and _month_ properties.

The _selected_ property however, does not accept dates such as "2017-1-1", it needs them to be in the double digit format, for example "2017-01-01".

For my use case, I am saving the selected date and having to manually add the "0" in front of days and months that are below 10, so that I can keep the selected date state, which is not ideal.
 
`const prefixZeroToNumber = number => ((number < 10) ? `` 0${number}  `` : number);`

I don't know whether the best solution is to change the _selected_ property to accept single digit numbers, or have the onDayPress event parameter output the double digit number, but I feel like this will be a common use case that people will have to work around.

**Comment by tautvilas** [comment]
Hi, thanks for feedback.

onDayPress returns single digit because it is returning integer and not a string. Since onDayPress also returns timestamp I would suggest creating date object with date library that you are using and then formatting it to YYYY-MM-DD datestring.

Another (easier) approach is just to pass the timestamp from `onDayPress` to `selected`.

**Comment by tautvilas** [comment]
Hey, added `dateString` property to all objects returned in callbacks. This means that now you can also get `YYYY-MM-DD` string without doing manual conversion

https://github.com/wix/react-native-calendars/#usage
