### ISSUE TITLE
Showing google calendar in agenda is rendering very slow

### ISSUE THREAD

**Issue by udarts** [wix/react-native-calendars#418]
I am already showing a google calendar in the agenda, but it is rendering crazy slow.
It takes 10 seconds or longer before the items are shown.

I basically used the default code for agenda, and modified the loaditems (at the screen agenda), to add the google cal items, which works, but is very very slow.

When I check the console.log on the items, they are there quick, but it seems the rendering takes a long time. How can that be adjusted?

**Comment by Devhound** [comment]
@udarts can you show how you loaded the data from google's calendar api? Do you have a lot of calendar events being loaded?  I think you will have to do some sort of pagination request to break it up.

**Comment by udarts** [comment]
@Devhound this is how I load data from google calendar api (changed some sensitive data):

```javascript 
async loadItems(day) { 
        const CALENDAR_ID = 'cal_ID';
        const API_KEY = 'API_KEY';
        const beginDate = moment();
        let url = 'https://www.googleapis.com/calendar/v3/calendars/${CALENDAR_ID}/events?key=${API_KEY}&timeMin=${beginDate.toISOString()}&singleEvents=true&orderBy=startTime';
        try {
            let response = await fetch(url);
            let data = await response.json();
            const events = data.items;
            if (events.length > 0) {
                const newItems = {};
                for (let i = 0; i < 85; i++) {
                    const time = day.timestamp + i * 24 * 60 * 60 * 1000;
                    const strTime = this.timeToString(time);                        
                    for (let j = 0; j < events.length; j++) {
                        const event = events[j];
                        const sTime = event.start.dateTime || event.start.date;
                        const eTime = event.end.dateTime || event.end.date;
                        const csTime = moment(sTime).format('YYYY-MM-DD');
                        const ceTime = moment(eTime).format('YYYY-MM-DD');
                        const csTime2 = moment(sTime).format('LT');          
                        const ceTime2 = moment(eTime).format('LT');
                        if (!newItems[strTime]) {
                            newItems[strTime] = [];
                        }
                        if(strTime === csTime) {
                            newItems[strTime].push({
                                title: event.summary,
                                startTime: csTime2,
                                endTime: ceTime2,
                                description: event.description
                            })
                        }
                    }
                }
                this.setState({
                    items: newItems
                });
            }
        } catch (error) {
            console.error(error);
        }
    }
```

I hope you have an idea on how to fix this.

**Comment by Devhound** [comment]
So I noticed that changing days and opening the month view would repeatedly execute the loaditems() function. I had to force it to only execute once in order to click the days without it freezing. 

Now, regarding the actually fetching of json data from google. That does seem to be slow even with max results set to like 100. I’m going to see if I can set up some sort of pagination where it only request one day at a time based on the rowHasChanged() function.

**Comment by udarts** [comment]
I only use the agenda view, as it is not needed to have the month view there as well (in my case).

**Comment by Devhound** [comment]
@udarts I found a solution with the default agenda view. I basically utilize the onDayPress parameter and only load the selected day. I also limit the agenda view to the selected day. Loads fast but had trade off having a long list of days since it was very buggy otherwise trying to load each day on the rows changed. But like you said, you don't need the month view so this might not be ideal for you.
