### ISSUE TITLE
onDayPress not working on Debug JS Remotely

### ISSUE THREAD

**Issue by ihusak** [wix/react-native-calendars#466]
## Environment
* `"react-native-calendars": "^1.18.2"`:
* `"react-native": "0.53.0"`:
## Also specify:
* `Redmi 5A/Android 7.1.2"`:

## Reproducible Demo

After updating to `^1.18.2` **onDayPress** not workind on debug mode, just when I turned off debug mode it's working.

Can you have any ideas?

**Comment by GaetanB999** [comment]
hello, same issue for me.
sometimes it work, sometimes not ...

**Comment by thetrevlore** [comment]
+1.

It works on an emulator for me on latest current version (1.19.3), even with remote debugging selected. It just doesn't work with an external device.

**Comment by thetrevlore** [comment]
I figured out the problem for me. The time on the external device and the time on my computer was off.

1. run this command: `adb shell date && date`
 - Mine was only off by 4 milliseconds. But it was still causing the issue.

To fix:
1. On your laptop/host computer go to your time and date settings and turn off and on "Set date and time automatically"
2. On the device turn off and on "Automatic date & time" AND "Automatic time zone"
Took a couple tries, and I restarted both devices.
Then just run that command to keep checking until both devices are synced. `adb shell date && date`

**Comment by thetrevlore** [comment]
I figured out the issue for me. I received this error at some point:
```diff
- Attempted to transition from state 'RESPONDER_INACTIVE_PRESS_IN' to 'RESPONDER_ACTIVE_LONG_PRESS_IN', which is not supported. This is most likely due to 'Touchable.longPressDelayTimeout' not being called.
```

The problem was that the time on the device and time on my computer were not synced up. If it's off even by 1 millisecond, onDayPress won't fire.
That's why if I used an emulator it was fine (same clock). And when I would run it on a release build on a physical device, not connected to my computer, it was fine.

To check this:
1. Run this command in terminal from anywhere to check if it's synced: `adb shell date && date`
2. on your laptop go to your time and date settings and turn off and on "Set date and time automatically"
3. on the device turn off and on "Automatic date & time" AND "Automatic time zone"
4. repeat until they're synced.

Still, my clocks aren't always exactly synced. Like right now it's like 1/2 ms off. So sometimes it fires and sometimes it doesn't. Just depends on if the ms are the same or not.
