### ISSUE TITLE
Is react-native-calendars working on web?

### ISSUE THREAD

**Issue by iCarbajo** [wix/react-native-calendars#521]
## Description

Im trying to set up this library in a proyect that requires native apps and web, and its working on native apps but not on web. The Calendar component its fine, but the CalendarList and Agenda doesn't show any calendar.
Is there any other configuration to do to get the components working on web?
The same project on the android emulator runs and works fine.
## Expected Behavior

CalendarList and Agenda working on web

## Observed Behavior

I dont saw any error on console

## Environment

To start the project i used "create-react-native-app --with-web-support" and then installed the latest version of react-native-calendars
then in the webpack.config in order to get the project compiled correctly added "es2017", "stage-0" presets on babel-loader.

* `npm ls react-native-calendars`: react-native-calendars@1.19.3
* `npm ls react-native`:react-native@0.55.4

Sorry about my english

**Comment by iCarbajo** [comment]
Anyone getting the same error? Im the only one?

**Comment by mogarick** [comment]
Hi @iCarbajo 
I'm having te same problem. I'm trying to render CalendarList without success. The only thing I see is a 1 pixel red dot.

**Comment by jkepps** [comment]
I'm having the same issue as @mogarick. Anyone find a solution?

**Comment by julhernandezv** [comment]
Hi @iCarbajo
I'm having the same problem to render Agenda on web, the calendar isn't working.
Anyone find a solution?

**Comment by riebel** [comment]
Hi @iCarbajo, hi @mogarick and hi @julhernandezv 

Again, did anyone find a solution?

**Comment by cglacet** [comment]
Compatible I don't think it is, but I managed to build the project at least. Here is how (I'll give the complete process, maybe someone can point out errors or improvements): 

```bash
npm install --save react-native-calendars
```
If you import Calendar at this point you'll get this error: 

```bash 
./node_modules/react-native-calendars/src/agenda/index.js
SyntaxError: /Users/cglacet/Voyance/client/node_modules/react-native-calendars/src/agenda/index.js: Support for the experimental syntax 'classProperties' isn't currently enabled (32:22):

  30 |  */
  31 | export default class AgendaView extends Component {
> 32 |   static displayName = 'Agenda';
     |                      ^
  33 |
  34 |   static propTypes = {
  35 |     /** Specify theme properties to override specific styles for calendar parts. Default = {} */

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

I fixed this error by using the same strategy as presented in [using React Native Elements on the web](https://react-native-elements.github.io/react-native-elements/docs/web_usage/), which is: 

```bash
npm install --save-dev @babel/plugin-proposal-class-properties customize-cra react-app-rewired
```

Then I created a `config-overrides.js` file in the root of my project with the following content: 

```js
const path = require('path');
const { override, addBabelPlugins, babelInclude } = require('customize-cra');

module.exports = override(
  ...addBabelPlugins('@babel/plugin-proposal-class-properties'),
  babelInclude([
    path.resolve(__dirname, 'src'),
    path.resolve(__dirname, 'node_modules/react-native-calendar'),
  ])
);
```

I finally replaced all occurrences of `react-scripts` by `react-app-rewired` in the `scripts` section of my `package.json` file. Once this is done, I can't try to build the project again. But this time I got the following error: 

```bash 
./node_modules/react-native-swipe-gestures/index.js
SyntaxError: /Users/cglacet/Voyance/client/node_modules/react-native-swipe-gestures/index.js: Unexpected token (121:11)

  119 |
  120 |   render() {
> 121 |     return <View {...this.props} {...this._panResponder.panHandlers} />;
      |            ^
  122 |   }
  123 | }
  124 |
```

This (I think) is because the `babelInclude` should even include indirect dependencies (no idea how this works and why this is required), but adding `react-native-swipe-gestures` to the `babelInclude` solved that last build problem. In the end, my `config-overrides.js` file contains the following:

```js
const path = require('path');
const { override, addBabelPlugins, babelInclude } = require('customize-cra');

module.exports = override(
  ...addBabelPlugins('@babel/plugin-proposal-class-properties'),
  babelInclude([
    path.resolve(__dirname, 'src'),
    path.resolve(__dirname, 'node_modules/react-native-calendar'),
    path.resolve(__dirname, 'node_modules/react-native-swipe-gestures'),
  ])
);
```

I think this project should provide documentation for this as this is not what I would call a very simple information to get …

In the end the calendar get displayed but colors and marking do not seem to work yet for me.
