### ISSUE TITLE
feat(Calendar) Add RTL support

### ISSUE THREAD

**Issue by naomipol** [wix/react-native-calendars#566]
## Description

The Calendar could not be displayed correctly for RTL languages.

## Expected Behavior

Have a RTL prop in Calendar, when set to true the next changes should take place: The calendar week will be displayed in reversed order, starting from Sunday on the right, and click on the right arrow will display the previous month instead of the next one (and vise versa).

## Implementation

I could put some effort on creating a pull request for this, let me know if wanted, along with initial implementation details.

Thanks

**Comment by dalwadani** [comment]
That would be amazing

**Comment by naomipol** [comment]
I was able to achieve a RTL calendar without changing the existing source code, by changing the flex-direction to `row-reverse` and rendering the arrows in the opposite direction:
```jsx

<Calendar theme={'stylesheet.calendar.main': {
                        week: {
                          marginTop: 7,
                          marginBottom: 7,
                          flexDirection: isRTL ? 'row-reverse' : 'row',
                          justifyContent: 'space-around'
                        }
                       },
                  'stylesheet.calendar.header': {
                        header: {
                           flexDirection: isRTL ? 'row-reverse' : 'row',
                          justifyContent: 'space-between',
                          paddingLeft: 10,
                          paddingRight: 10,
                          alignItems: 'center',
                          height: 45
                        },
                        week: {
                          marginTop: 7,
                           flexDirection: isRTL ? 'row-reverse' : 'row',
                          justifyContent: 'space-around'
                        }}
                      }}
            renderArrow={direction => <Icon type="ionicon"
                                            name={direction === 'left'
                                               ? (isRTL ? 'arrow-forward' : 'arrow-back')
                                               : (isRTL ? 'arrow-back' : 'arrow-forward')}
                                               />}
    />

**Comment by dalwadani** [comment]
Thanks. It's working now. However, when using CalendarList in horizontal mode, the swiping direction of the calendar is still LTR. I *think* we need to pass inverted prop to the flatlist component here:
https://github.com/wix/react-native-calendars/blob/60108b56c49216e35567784423b45cbbe6476b90/src/calendar-list/index.js#L200 
Can we achieve this without changing the code?

**Comment by KirankumarDafda** [comment]
Are you sure @dalwadani that this apply for all days and date and, showing proper dates on the days of the month, like, 1st Sep, 2018 Saturday, 2nd Sep, 2018 Sunday, 3rd Sep, 2018 Monday, etc... ?

**Comment by saadiyakazi** [comment]
@naomipol 
Hi
I have used the solution that you mentioned about for RTL .It works.
But for setting the markingType={"period"} 
I want the borderRadius also to be inverted since now it is showing up this way 
<img width="412" alt="Screen Shot 2020-04-21 at 12 18 55 PM" src="https://user-images.githubusercontent.com/50286168/79848928-705d0c00-83ca-11ea-8488-e2ddbe89f8f2.png">

**Comment by elie-chaaban** [comment]
@saadiyakazi did you manage to fix this?

**Comment by esvanegas** [comment]
Hey everyone!, I don't know if this is the correct place to post this, but this is the most related discussion about it; After hours and hours looking on how to reverse the order of months in calendar-list I found a workaround that works, I don't know if it is the best approach but worked for me.

So the first thing we must do is to transform the flat list depending on what you want to achieve, if you have a horizontal list, you must transform the list on X axis otherwise Y, then do the same but with the calendar container. In mi case I had working in a vertical list so the example above is based on that.

```typescript
theme={{
        'stylesheet.calendar.main': {
          container: {
            transform: [{scaleY: -1}],
          },
        },
        'stylesheet.calendar-list.main': {
          flatListContainer: {
            flexDirection: 'row-reverse',
            transform: [{scaleY: -1}],
          },
        },
}}
```

And that's all! you have your calendar list in reverse order! Starting with the current month and sliding down to look past months. For more information can take a look on this [page](https://maxammann.org/posts/2021/01/react-native-invert-scrollview/)

![Simulator Screen Shot - iPhone 14 - 2023-04-12 at 22 27 05](https://user-images.githubusercontent.com/44588624/231641693-3a2b37c8-17bd-4245-9776-aeb3d59d4fca.png)
