### ISSUE TITLE
How to change agenda pull down icon?

### ISSUE THREAD

**Issue by Oakyden** [wix/react-native-calendars#590]
Hi

I am looking to change the icon used to bring down the calendar view when viewing Agenda.

Right now its a small line, i'd like to replace it with a delta arrow or similar.

<img width="342" alt="screen shot 2018-08-08 at 08 56 07" src="https://user-images.githubusercontent.com/35015858/43824088-ee25afba-9ae8-11e8-9829-79562641f2c2.png">

**Comment by DavidNorena** [comment]
Let's help more people, please post a [new stackoverflow question](https://stackoverflow.com/questions/ask), under the tags [react-native, react-native-calendars]  because this is more a issue / bug tracker.

I'll be very glad to help you in [SO](http://www.stackoverflow.com), we can reach a lot more people with your same question 😀😀😀😀😀😀.

**Comment by Oakyden** [comment]
Thanks. Here you go https://stackoverflow.com/questions/51821085/change-the-pull-down-icon-for-react-native-calendars
