### ISSUE TITLE
How works the agenda?

### ISSUE THREAD

**Issue by apppro123** [wix/react-native-calendars#670]
Hello

Can somebody pls explain me how the agenda works. I don't know how loadItemsForMonth, renderItem or renderEmptyDate works. When do these get called and what arguments do they get? And is it possible to work without loadItemsForMonth if every item already has the date as the key?

Thank you

**Comment by apppro123** [comment]
Or can somebody post an example of his functions (especially of loadItemForMonth)? Because i don't get it just with the information and example code of agenda.
That would be really nice!! :)

**Comment by apppro123** [comment]
Hello, is anybody out there who can help me?????

**Comment by AsadSaleh** [comment]
Hey, sorry for my late help. 

But you can actually copy-and-paste the provided code to see what it does. Here is the link [https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js]

**When do these get called**: I believe it is on the initial render of the component, and will be called again every re-render. Just like all React components does.

**what arguments do they get**: I believe you can see that in the main page of this repo.

**is it possible to work without loadItemsForMonth if every item already has the date as the key**:
I can't answer that yet as I'm still trying to use it.

Hope that helps, even tough it's almost been a month since u asked.
