### ISSUE TITLE
Support for custom CalendarHeader

### ISSUE THREAD

**Issue by varunon9** [wix/react-native-calendars#745]
## Description

Feature Request-

We should be able to implement our own Calendar Header, e.g. I want both navigation arrows to be on right side and Today's date in left side. 

![image](https://user-images.githubusercontent.com/9805036/53233476-86324c80-36b3-11e9-964c-eae7c49f9c66.png)

## Expected Behavior

It should support custom header.

## Observed Behavior

Right now there is no support for custom header.

**Comment by IronTony** [comment]
@varunon9 hi, the numbers under the date are a custom mod of this package?

**Comment by varunon9** [comment]
That is custom Day component `dayComponent={CalendarDayComponent}`
If you are interested in implementing something like above mock, read the story here-
https://medium.com/@varunon9/how-i-built-horizontal-as-well-as-grid-calendar-in-react-native-using-react-native-calendars-eb7a2edcc5db

**Comment by IronTony** [comment]
you are the man. thank you so much for the answer and the tutorial

**Comment by hernanif1** [comment]
The way I found of achieving it
```tsx

// inside the theme property
'stylesheet.calendar.header': {
      headerContainer: {
        backgroundColor: 'orange',
        position: 'absolute',
        flexDirection: 'row',
        left: 0,
        gap: 20,
      },
      header: {
        backgroundColor: 'purple',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        paddingLeft: 10,
        paddingRight: 10,
        marginTop: 6,
        alignItems: 'center',
      },
    },```
    
this will make your component header to look like as this:
<img width="326" alt="Screenshot 2023-09-13 at 11 38 12" src="https://github.com/wix/react-native-calendars/assets/1771727/2c94aa73-3527-4507-aa84-678410950687">


but the right arrows will be on top of the left arrow because of the hitslop
since the arrow has a touchable component around it and it doesn't accept a gap, the only way I found was adding a custom icon with some margin/padding


```tsx
      <Calendar
        renderArrow={direction =>
          direction === 'right' ? (
            <ScheduleArrow direction="right" />
          ) : (
            <ScheduleArrow direction="left" className="mr-10" />
          )
        }
        ...
        ```
 
<img width="335" alt="Screenshot 2023-09-13 at 11 40 33" src="https://github.com/wix/react-native-calendars/assets/1771727/24ca6022-fb32-4364-8a20-5084ac2bbeaf">

Now it works correctly in my case
"react-native-calendars": "^1.1300.0",

**Comment by thundron** [comment]
@hernanif1 I tried your solution but absolutely nothing happens, I'm not sure why - version is v1.1301
