### ISSUE TITLE
Trying to render current 'day' on 'renderEmptyData'

### ISSUE THREAD

**Issue by GuillaumeRZ** [wix/react-native-calendars#776]
Hi,

I am render an agenda, with date. Some have items, some not.

Each renderItem display automatically the current selected date on the left :
```
renderItem={item => (
          <View>
            <Text>{item.title}</Text>
            <ValidButton
              text="Reserve it"
              onPress={() => console.log("Reserved !"}
            />
          </View>
        )}
```

But on renderEmptyData, there is not the current selected date on the left :
```
renderEmptyData={() => (
          <View>
            <Text>Not available</Text>
            <AlertButton
              text="Get a notification for this day"
              onPress={() => console.log(`Notification`)}
            />
          </View>
        )}
```

I want to dislpay the day on the left for each selected day on the left, like for this example :
![](https://raw.githubusercontent.com/wix/react-native-calendars/master/demo/agenda.gif)

**Comment by danielmartinprieto** [comment]
I agree this should be the default behaviour, I was about to ask the same question when I saw your issue.

In order to accomplish what we want, we need to assign an empty array for all the days we want to be displayed, like `items={{ '2019-04-02': [], ...otherItems }}`.

I wonder if there is an easier way of doing this, as adding keys + empty array for _all_ items without content seems far from ideal.
