### ISSUE TITLE
No arrows show when using with react-native-web

### ISSUE THREAD

**Issue by obiwankenoobi** [wix/react-native-calendars#801]
## Description

No arrows show when using with `react-native-web`

## Expected Behavior

Show arrows just like in mobile

## Environment

Please run these commands in the project folder and fill in their results:

* `react-native-calendars@1.66.0 `:
* `react-native@0.55.4`:

Also specify:

1. Phone/emulator/simulator & version:
Web

**Comment by cobrAJ** [comment]
I'v got the same problem as yours, but I found this may happened with TouchableOpacity Component, It has render two part to show, one is touch part, another is show part ,the show part has no width & height, I can fixed it in css solution , but I can't do it in Stylesheet func. So still not working.

**Comment by oshimayoan** [comment]
Just found the workaround for this. You can use `renderArrow={(direction) => (<Arrow />)}` to make the arrow appear on web.

**Comment by EyMaddis** [comment]
Without looking at the code: The `<Image .../>` component probably does not have width/height set, so they do not display on the web.

**Comment by gabeboileau** [comment]
I'm also having the same issue. I attempted @oshimayoan 's solution, however, there is no component `<Arrow />` that exists. I've also tried to create my own Arrow component, but I can't figure out how to change months, since there is no callback to change month. I've changed the `current` date using react state, but it does not update the component. Any help would be appreciated!

**Comment by oshimayoan** [comment]
@gabeboileau You have to use your own Arrow component for that. 

> but I can't figure out how to change months, since there is no callback to change month

The calendar will change it for you whenever you click/press the arrow button.

**Comment by gabeboileau** [comment]
@oshimayoan Yea, I've created a custom button with an icon as my `Arrow`. It's as follow 

```
       renderArrow={(direction) => {
          if (direction == "left")
            return (
              <Button>
                <Icon name="keyboard-arrow-left" type="MaterialIcons" />
              </Button>
            );
          if (direction == "right")
            return (
              <Button>
                <Icon name="keyboard-arrow-right" type="MaterialIcons" />
              </Button>
            );
        }}
```

However, how do I change the month forward and backward? I've changed the `current` date property, but it's not changing the component. 

Thanks for the quick reply.

**Comment by oshimayoan** [comment]
Usually, the component will automatically change the month forward and backward every time you click the arrow button. But if you want to get the changed date, which includes the month, you can use `onDayPress` prop for that.

**Comment by gabeboileau** [comment]
@oshimayoan Thank you for all your help. I figured out what the problem was. The component I was returning was a `Button` with an `Icon` within it. I changed that to just returning the `Icon` and it was put within a pre-existing button that the `Calendar` handles under the hood for changing the months. 

Thanks again!

**Comment by manueldeprada** [comment]
Easy fix that works for me:

```
      <Calendar
        theme={{
          arrowWidth: 20,
          arrowHeight: 20,
        }}
```
