### ISSUE TITLE
Increase Height of the Closed Calendar in Agenda

### ISSUE THREAD

**Issue by ahmad6242** [wix/react-native-calendars#821]
## Description

I want to increase the height of the Calendar when it is closed.

## Expected Behavior

I want to show more than one rows when the calendar is closed

## Observed Behavior

It only shows one row of the Calendar.
// agenda container style
style={{ height:500, backgroundColor: 'yellow' }} ---> Height not working

![image](https://user-images.githubusercontent.com/12858657/57767712-11ebd000-771b-11e9-845a-d0fd2e00ea7b.png)

## Environment

* `react-native-calendars@1.110.0`:
* `react-native@0.59.5`:

**Comment by robertodalessio1981** [comment]
I have the dame issue!

**Comment by HaswinVidanage** [comment]
+1

**Comment by LucasHimelfarb** [comment]
I'm having the same problem, only mine is 5 px

**Comment by HaswinVidanage** [comment]
+ 1

**Comment by rheutz** [comment]
I fixed this by changing the following code.
 `   calendarOffset() {
-    return 90 - (this.viewHeight / 2);
+    const offset = Platform.OS === 'ios' ? 90 : 100
+    return offset - this.viewHeight / 2
   }`

**Comment by robertodalessio1981** [comment]
worked fine  for my issue, thanks!

**Comment by ahmad6242** [comment]
@robertodalessio1981 
@rheutz 
how did you do it? 

i have applied that code
react-native-calendars/src/agenda/index.js
calendarOffset() {
const offset = Platform.OS === 'ios' ? 90 : 100
return offset - this.viewHeight / 2
}


after that i have set the height of the calendar in the style but still it is not working. The height of the Calendar is same as before. 
Please assist.
Thanks.

**Comment by robertodalessio1981** [comment]
in my case I didn't have to change the height, the issue was that with the default height (one week), it was slightly undersized.

modifying react-native-calendars/src/agenda/index.js with the code above, it is solved

**Comment by Areeb0206** [comment]
Go to the same file, in src/index.js, 
By default height is mentioned at line 20, , u can modify it

**Comment by FlyFishCode** [comment]
I use chinese ，because I'm english not good。
基于上面伙计们得改动，可以改动如下几点来修改高度
1.在 react-native-calendars/src/agenda/index.js 中。第 16行 const HEADER_HEIGHT = 104; 改成204或者更高
2.无数据渲染 renderEmptyData渲染得元素中样式 marginTop 高度为 HEADER_HEIGHT 
3.有数据渲染 renderItem={(item, firstItemInDay) =>
            renderItem(item, firstItemInDay)
   }
like this； const renderItem = (item: any, isFirst: boolean) => {
      return (
        <View style={isFirst ? {marginTop: 100} : null}>
          <ScrollView showsVerticalScrollIndicator={false}>
            <RenderDayMatch item={item} />
          </ScrollView>
        </View>
      );
    };
marginTop：100 或者其它值都可以，看你得要求
改动前：
![1](https://user-images.githubusercontent.com/37266998/160543356-401fab12-0978-43af-b92e-59f14895e8e5.jpg)
改动后：
![2](https://user-images.githubusercontent.com/37266998/160543414-d6bc2fcb-fc74-492b-a2cc-d3a1baf4d37f.jpg)
但是还有有一个问题，就是有数据时候渲染得元素，左侧日期没有展示出来，我猜测，左侧日期跟渲染得数据不是在同一个父元素下。
![3](https://user-images.githubusercontent.com/37266998/160543789-25fbd514-d6db-46e2-9c80-b7d2bba00377.jpg)

如果有小伙伴可以提供后续得解决办法，那是最好的了
