### ISSUE TITLE
recieveTouches RCTEventEmitter height NaN

### ISSUE THREAD

**Issue by iOSUser110** [wix/react-native-calendars#874]
## Description

First time on tap of that expandable line tap , giving error : Error calling RCTEventEmitter.recieveTouches 
Unhandled Js Exceptions 1097 : RCTView {height:"<<NaN>>} is not usable as a nativemethod argument 

## Expected Behavior

On tap of that hosrizontal bar for expansion it should expand normally , it is happening only first time 

## Observed Behavior

screen come with the below error for the first time 

```
Error calling RCTEventEmitter.recieveTouches 
Unhandled Js Exceptions 1097 : RCTView {height:"<<NaN>>} is not usable as a nativemethod argument 
```

## Environment
xcode - 10.2.1
react native - 0.60.0
react-native-calendars - 1.198.0

Phone/emulator/simulator & version:
iPhone 7
iOS 11.4.1

**Comment by habibiazmi123** [comment]
I also have a problem, someone can help ?

**Comment by iOSUser110** [comment]
do we need to pass height explicitly ?? is there any workaround ?
Please anybody ?

**Comment by iOSUser110** [comment]
Invariant Violation: Invariant Violation: Invariant Violation: [1097,"RCTView",{"height":"<<NaN>>"}] is not usable as a native method argument


This error is located at:
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at expandableCalendar/index.js:465)
    in RCTView (at View.js:45)
    in View (at expandableCalendar/index.js:464)

**Comment by mtieltjes** [comment]
I boiled it down to this:

In the constructor the [`_wrapperStyles`](https://github.com/wix/react-native-calendars/blob/375fd756d664da5e84fdcf5d9b18126c5f26924f/src/expandableCalendar/index.js#L84) gets initialized with an empty style object.

Next, in [`handlePanResponderEnd`](https://github.com/wix/react-native-calendars/blob/375fd756d664da5e84fdcf5d9b18126c5f26924f/src/expandableCalendar/index.js#L268) the height gets set to the height in the `wrapperStyles.style`, begin `undefined` at that point.

Next, when dragging/touching the knob, [`handlePanResponderMove`](https://github.com/wix/react-native-calendars/blob/375fd756d664da5e84fdcf5d9b18126c5f26924f/src/expandableCalendar/index.js#L253) will set the `wrapperStyles.style.height` to what is stored in `this._height`, which is undefined as per above. (Apparently undefined+x (= NAN) is higher than a number)

Finally in [`bounceToPosition`](https://github.com/wix/react-native-calendars/blob/375fd756d664da5e84fdcf5d9b18126c5f26924f/src/expandableCalendar/index.js#L282) the NAN height is set to the animated component, triggering the following error:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/9537966/72811072-2e9fb680-3c5f-11ea-84b4-824f066061f0.png">


1 'fix' I found is to set the `startHeight` as height in `_wrapperStyles.style`. Will provide a PR for that if it turns out to reliably fix the error in my situation
